[org.pisilinuxproject.kaptan.checkdaemon]
Name=Daemon status checker
Description=Checks the status of a daemon (enabled/disabled/not installed)
Policy=yes
Persistence=session

[org.pisilinuxproject.kaptan.enabledaemon]
Name=Daemon enabler
Description=Enables a specific daemon
Policy=auth_admin
Persistence=session

[org.pisilinuxproject.kaptan.disabledaemon]
Name=Daemon disabler
Description=Disables a specific daemon
Policy=auth_admin
Persistence=session
